language: node_js
os: linux
node_js:
  - 12 # use nodejs v12 LTS
cache: npm
branches:
  only:
    - src # build master branch only
    - dev-hexo # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: src
  local_dir: public
  target_branch: master